In [90]:
import csv

with open('winequality-red.csv') as f:
    wines = list(csv.reader(f, delimiter=';'))
    
print(wines[:3])
print len(wines)

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]
1600


In [29]:
q = wines[0].index("quality")

qualities = [float(row[q]) for row in wines[1:]]
print sum(qualities) / len(qualities)

5.63602251407


In [41]:
import numpy as np

w = np.array(wines[1:], dtype=np.float)
print w.shape
print w[1]
w

(1599, 12)
[  7.8      0.88     0.       2.6      0.098   25.      67.       0.9968
   3.2      0.68     9.8      5.    ]


array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [55]:
e = np.zeros((3, 4, 2))
e

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [61]:
np.random.rand(3, 4, 2)

array([[[ 0.19740365,  0.14583291],
        [ 0.20716933,  0.05765918],
        [ 0.09131899,  0.38735245],
        [ 0.28595527,  0.86321   ]],

       [[ 0.01228166,  0.88498685],
        [ 0.16735236,  0.28897098],
        [ 0.33284498,  0.31601923],
        [ 0.13793591,  0.93040981]],

       [[ 0.50800754,  0.07987141],
        [ 0.19841556,  0.2329591 ],
        [ 0.07144676,  0.41172807],
        [ 0.47489495,  0.030805  ]]])

In [133]:
wines = np.genfromtxt('winequality-red.csv', delimiter=';', skip_header=1)
wines

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [65]:
wines[2,3]

2.2999999999999998

In [66]:
wines[2][3]

2.2999999999999998

In [68]:
wines[0:3,3] # slicing is by reference; MATLAB copies stuff over

array([ 1.9,  2.6,  2.3])

In [69]:
wines[:,10] = 50
wines[:,10]

array([ 50.,  50.,  50., ...,  50.,  50.,  50.])

In [71]:
wines[(1,1)]

0.88

In [73]:
wines.dtype

dtype('float64')

In [82]:
print wines.astype('string').dtype.name
wines.astype('int')

string256


array([[ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       ..., 
       [ 6,  0,  0, ...,  0, 50,  6],
       [ 5,  0,  0, ...,  0, 50,  5],
       [ 6,  0,  0, ...,  0, 50,  6]])

In [80]:
wines.astype(np.int32)

array([[ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       ..., 
       [ 6,  0,  0, ...,  0, 50,  6],
       [ 5,  0,  0, ...,  0, 50,  5],
       [ 6,  0,  0, ...,  0, 50,  6]], dtype=int32)

In [87]:
wines[:,q] += 10
wines[:,q]

array([ 25.,  25.,  25., ...,  26.,  25.,  26.])

In [98]:
x = wines[:,10] * wines[:,11] + 1
x

array([ 48.,  50.,  50., ...,  67.,  52.,  67.])

In [107]:
# broadcasting

x = np.array([[1, 2, 3], [4, 5, 6]])
print x
print x.shape
y = np.array([10, 100, 1000])
print y.shape
print x * y
y = np.array([[10, 100, 1000]])
print y.shape
print x * y

[[1 2 3]
 [4 5 6]]
(2, 3)
(3,)
[[  10  200 3000]
 [  40  500 6000]]
(1, 3)
[[  10  200 3000]
 [  40  500 6000]]


In [115]:
print x.sum()
print x.shape
print x.sum(0)
print x.sum(axis=0)
print x.sum(1)

21
(2, 3)
[5 7 9]
[5 7 9]
[ 6 15]


In [134]:
print wines[:,5] > 5
print wines[:,5] == 10
which = wines[:,5] == 10
#print wines[which, :]

# subsetting
high_quality = wines[:,11] > 7
print wines[high_quality,:][:3,:]

high_quality_and_alcohol = (wines[:,10] > 10) & (wines[:,11] > 7)
print wines[high_quality_and_alcohol,10:]

# wines[high_quality_and_alcohol,10:] = 20


[ True  True  True ...,  True  True  True]
[False False False ..., False False False]
[[  7.90000000e+00   3.50000000e-01   4.60000000e-01   3.60000000e+00
    7.80000000e-02   1.50000000e+01   3.70000000e+01   9.97300000e-01
    3.35000000e+00   8.60000000e-01   1.28000000e+01   8.00000000e+00]
 [  1.03000000e+01   3.20000000e-01   4.50000000e-01   6.40000000e+00
    7.30000000e-02   5.00000000e+00   1.30000000e+01   9.97600000e-01
    3.23000000e+00   8.20000000e-01   1.26000000e+01   8.00000000e+00]
 [  5.60000000e+00   8.50000000e-01   5.00000000e-02   1.40000000e+00
    4.50000000e-02   1.20000000e+01   8.80000000e+01   9.92400000e-01
    3.56000000e+00   8.20000000e-01   1.29000000e+01   8.00000000e+00]]
[[ 12.8   8. ]
 [ 12.6   8. ]
 [ 12.9   8. ]
 [ 13.4   8. ]
 [ 11.7   8. ]
 [ 11.    8. ]
 [ 11.    8. ]
 [ 14.    8. ]
 [ 12.7   8. ]
 [ 12.5   8. ]
 [ 11.8   8. ]
 [ 13.1   8. ]
 [ 11.7   8. ]
 [ 14.    8. ]
 [ 11.3   8. ]
 [ 11.4   8. ]]


In [141]:
# reshaping

print wines.shape
print np.transpose(wines).shape
print np.ravel(wines).shape
print wines[1,:].reshape(2, 6)

(1599, 12)
(12, 1599)
(19188,)
[[  7.8      0.88     0.       2.6      0.098   25.    ]
 [ 67.       0.9968   3.2      0.68     9.8      5.    ]]


In [148]:
# combining arrays

white_wines = np.genfromtxt("winequality-white.csv", delimiter=";", skip_header=1)
white_wines.shape

all_wines = np.vstack((white_wines, wines))
print all_wines.shape

all_wines = np.concatenate((wines, white_wines), axis=0)
print all_wines.shape

(6497, 12)
(6497, 12)


In [157]:
# challenge

z = np.zeros((3,4))
o = np.ones((6,4))
c = np.vstack((z, o))
print c
first_column = c[:,0]
print first_column

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[ 0.  0.  0.  1.  1.  1.  1.  1.  1.]


In [171]:
a = np.arange(1, 30, 2)
print a

a = a.reshape(3, 5)
print a

print a.shape
print a.ndim
print a.size
print a.dtype.name
print a.itemsize
print type(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]
(3, 5)
2
15
int64
8
<type 'numpy.ndarray'>


In [176]:
print np.arange(0, 10, 0.3)
x = np.linspace(0, 2 * np.pi, 100)
print np.max(x)
print np.min(x)
print np.sin(x)

[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9  4.2
  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1  8.4  8.7
  9.   9.3  9.6  9.9]
6.28318530718
0.0
[  0.00000000e+00   6.34239197e-02   1.26592454e-01   1.89251244e-01
   2.51147987e-01   3.12033446e-01   3.71662456e-01   4.29794912e-01
   4.86196736e-01   5.40640817e-01   5.92907929e-01   6.42787610e-01
   6.90079011e-01   7.34591709e-01   7.76146464e-01   8.14575952e-01
   8.49725430e-01   8.81453363e-01   9.09631995e-01   9.34147860e-01
   9.54902241e-01   9.71811568e-01   9.84807753e-01   9.93838464e-01
   9.98867339e-01   9.99874128e-01   9.96854776e-01   9.89821442e-01
   9.78802446e-01   9.63842159e-01   9.45000819e-01   9.22354294e-01
   8.95993774e-01   8.66025404e-01   8.32569855e-01   7.95761841e-01
   7.55749574e-01   7.12694171e-01   6.66769001e-01   6.18158986e-01
   5.67059864e-01   5.13677392e-01   4.58226522e-01   4.00930535e-01
   3.42020143e-01   2.81732557e-01   2.20310533e-

In [183]:
x = np.arange(1, 10, 2)
print x ** 2
x += x ** 2
print x

print x.sum()
print x.min()
print x.max()
print x.mean()
print x.var()
print x.std()
print x.cumsum()

[ 1  9 25 49 81]
[ 2 12 30 56 90]
190
2
90
38.0
1012.8
31.8245188495
[  2  14  44 100 190]


In [187]:
y = x + 10
print x + y
print np.exp(x)
print np.sqrt(x)

[ 14  34  70 122 190]
[  7.38905610e+00   1.62754791e+05   1.06864746e+13   2.09165950e+24
   1.22040329e+39]
[ 1.41421356  3.46410162  5.47722558  7.48331477  9.48683298]


In [197]:
# from f'n
def f(r, c):
    return r * 1000 + c
x = np.fromfunction(f, (5, 4), dtype=int)

# flatten
print x
print x.flatten()
for i in x.flat:
    print i    

# transpose
print x.T

[[   0    1    2    3]
 [1000 1001 1002 1003]
 [2000 2001 2002 2003]
 [3000 3001 3002 3003]
 [4000 4001 4002 4003]]
[   0    1    2    3 1000 1001 1002 1003 2000 2001 2002 2003 3000 3001 3002
 3003 4000 4001 4002 4003]
0
1
2
3
1000
1001
1002
1003
2000
2001
2002
2003
3000
3001
3002
3003
4000
4001
4002
4003
[[   0 1000 2000 3000 4000]
 [   1 1001 2001 3001 4001]
 [   2 1002 2002 3002 4002]
 [   3 1003 2003 3003 4003]]


In [202]:
# reshape (copy) vs resize (in place)
y = np.reshape(x, (4, 5))
print y
x.resize((4, 5))
print x

# stacking
print np.hstack((x, x))
print np.vstack((x, x))

[[   0    1    2    3 1000]
 [1001 1002 1003 2000 2001]
 [2002 2003 3000 3001 3002]
 [3003 4000 4001 4002 4003]]
[[   0    1    2    3 1000]
 [1001 1002 1003 2000 2001]
 [2002 2003 3000 3001 3002]
 [3003 4000 4001 4002 4003]]
[[   0    1    2    3 1000    0    1    2    3 1000]
 [1001 1002 1003 2000 2001 1001 1002 1003 2000 2001]
 [2002 2003 3000 3001 3002 2002 2003 3000 3001 3002]
 [3003 4000 4001 4002 4003 3003 4000 4001 4002 4003]]
[[   0    1    2    3 1000]
 [1001 1002 1003 2000 2001]
 [2002 2003 3000 3001 3002]
 [3003 4000 4001 4002 4003]
 [   0    1    2    3 1000]
 [1001 1002 1003 2000 2001]
 [2002 2003 3000 3001 3002]
 [3003 4000 4001 4002 4003]]


In [225]:
# views and copies -- pass by reference
a = np.arange(0, 20, 1).reshape(4, 5)
b = a
print b is a # ref

# views
c = a.view()
print c is a
print c.base is a
print c.flags.owndata
c.shape = 10, 2

c[0, 0] = 10000
print a # modifying c changes a

s = a[:, 1:3] # slicing returns a view
s[0,:] = -999
print a

# deepcopy
d = a.copy()
d[0, 0] = 1000
print a

True
False
False
False
[[10000     1     2     3     4]
 [    5     6     7     8     9]
 [   10    11    12    13    14]
 [   15    16    17    18    19]]
[[10000  -999  -999     3     4]
 [    5     6     7     8     9]
 [   10    11    12    13    14]
 [   15    16    17    18    19]]
[[10000  -999  -999     3     4]
 [    5     6     7     8     9]
 [   10    11    12    13    14]
 [   15    16    17    18    19]]


In [250]:
# indexing
a = np.arange(12) ** 2
print a

i = np.array([0, 3, 4, 10])
print a[i]

j = np.array([[1, 1], [3, 4]])
print a[j]

# check it out -- 2D indexing!
a.resize(3, 4)
i = np.array([0, 1, 2])
j = np.array([3, 2, 3])
print a[i, j]
l = [i, j] # indices in a list
print a[l]

# assign indices
a[l] = -1
print a

[  0   1   4   9  16  25  36  49  64  81 100 121]
[  0   9  16 100]
[[ 1  1]
 [ 9 16]]
[  9  36 121]
[  9  36 121]
[[  0   1   4  -1]
 [ 16  25  -1  49]
 [ 64  81 100  -1]]


In [247]:

# argmax

x = np.linspace(0, np.pi * 2, 10)
y = np.sin(x).reshape(5, 2)
print y
i = y.argmax(axis = 0)
print y[i, xrange(y.shape[1])]
j = y.argmax(axis = 1)
print y[xrange(y.shape[0]),j]

[[  0.00000000e+00   6.42787610e-01]
 [  9.84807753e-01   8.66025404e-01]
 [  3.42020143e-01  -3.42020143e-01]
 [ -8.66025404e-01  -9.84807753e-01]
 [ -6.42787610e-01  -2.44929360e-16]]
[ 0.98480775  0.8660254 ]
[  6.42787610e-01   9.84807753e-01   3.42020143e-01  -8.66025404e-01
  -2.44929360e-16]


In [261]:
# boolean indices

x = np.arange(0, 12).reshape(3, 4)
b = np.array([[1, 0, 0, 1], [0, 1, 1, 1], [0, 0, 0, 1]], dtype=bool)

print x[b]

# by rows and columns
r = np.array([1, 0, 1], dtype=bool)
c = np.array([1, 1, 0, 1], dtype=bool)
print x[r, :]
print x[:, c]

[ 0  3  5  6  7 11]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]


In [270]:
# linear algebra
a = np.array([[1.0, 2.0], [3.0, 4.0]])

print a
print a.transpose()

print np.linalg.inv(a)

b = np.arange(1, 7).reshape(2, 3)
print np.dot(a, b)

y = np.array([3, 8])
print np.linalg.solve(a, y)

print np.linalg.eig(a)

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[  9.  12.  15.]
 [ 19.  26.  33.]]
[ 2.   0.5]
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
